# #####################################################################
# Automatically generated by qmake (2.01a) ter abr 7 00:37:03 2009
# #####################################################################
QT += app \
    core
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += src/tabuleiro.h \
    src/tree.h
SOURCES += src/tabuleiro.cpp \
    src/main.cpp
